export enum DIControllerType {
  CONTROLLER = 'CONTROLLER',
  API_VERSION_CONTROLLER = 'API_VERSION_CONTROLLER',
  AUTH_CONTROLLER = 'AUTH_CONTROLLER'
}

export enum DIServiceType {
  SAMPLE_SERVICE = 'SAMPLE_SERVICE',
  DEFAULT_LOGGER_SERVICE = 'DEFAULT_LOGGER_SERVICE',
  CONSOLE_LOGGER_SERVICE = 'CONSOLE_LOGGER_SERVICE',
  FILE_LOGGER_SERVICE = 'FILE_LOGGER_SERVICE'
}

export enum DIDecoratorsType {
  REST_API_DECORATOR_FACTORY = 'REST_API_DECORATOR_FACTORY'
}
